# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Tales of a Software Engineer
subtitle: "Version 2.0"
email: philip.limbeck@gmail.com
name: "Philip Limbeck"
description: >- # this means to ignore newlines until "baseurl:"
  This is a blog about science, finance, computer science, programming and 
  travelling (if it so happens). Knowledge is key, so is wisdom. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: jekyllrb
github_username:  phil3k3
timezone: Europe/Amsterdam


sidebar:
  - title: "Title"
    image: http://placehold.it/350x250
    image_alt: "image"
    text: "Some text here."
  - title: "Another Title"
    text: "More text here."

# Build settings
theme: minimal-mistakes-jekyll
plugins:
  - jekyll-feed

minimal_mistakes_skin: "air"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      author_profile: true
      show_date: true
      read_time: true

social:
  links: 
    - "https://www.linkedin.com/in/philip-limbeck-78354883/"

analytics:
  provider: "google"
  google:
    tracking_id: "250129659"
    anonymize_ip: true


author:
  name: "Philip Limbeck"
  avatar: "/assets/images/image-big.jpg"
  bio: "My awesome blog"
  location: "Amsterdam, Netherlands"
  links: 
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/phil3k3"

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
