source 'https://rubygems.org'

gem 'jekyll', '4.3.3'

group :jekyll_plugins do
  gem 'jekyll-paginate'
  gem 'jekyll-sitemap'
end

gem "eventmachine", "1.2.7"
gem "webrick", "~> 1.8"
gem "rexml", "~> 3.2"
